- name: create kubernetes dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ kubernetes_config_dir }}"
    - "{{ kubernetes_script_dir }}"
    - "{{ kubernetes_podmaster_dir }}"
  become: yes
  tags:
    - k8s-master

# kubelet-wrapper is only available on CoreOS 962.0.0+ so we make sure its here
# to ensure backwards compatability.
# See https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html
- name: download kubelet-wrapper
  become: yes
  get_url:
    url: "{{ kubernetes_kubelet_wrapper }}"
    dest: /opt/bin/kubelet-wrapper
    mode: 0775
  tags:
    - k8s-master

- name: create service account users
  become: yes
  lineinfile:
    dest: "{{ kubernetes_users_dir }}/known_users.csv"
    create: yes
    line: '{{ item.value.pass }},{{ item.key }},{{ item.value.role }}'
  with_dict: "{{ k8s_users }}"
  notify:
    - restart kubelet
  tags:
    - k8s-master

# master
- name: deploy kubelet service
  become: yes
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify:
    - reload systemd
    - restart kubelet
  tags:
    - k8s-master

- name: ensure kubelet is running
  become: yes
  service:
    name: kubelet
    state: started
    enabled: yes
  tags:
    - k8s-master

- name: deploy k8s-master manifests
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: kube-proxy.yaml.j2
      dest: "{{ kubernetes_manifest_dir }}/kube-proxy.yaml"
    - src: kube-apiserver.yaml.j2
      dest: "{{ kubernetes_manifest_dir }}/kube-apiserver.yaml"
    - src: kube-podmaster.yaml.j2
      dest: "{{ kubernetes_manifest_dir }}/kube-podmaster.yaml"
    - src: kube-controller-manager.yaml.j2
      dest: "{{ kubernetes_podmaster_dir }}/kube-controller-manager.yaml"
    - src: kube-scheduler.yaml.j2
      dest: "{{ kubernetes_podmaster_dir }}/kube-scheduler.yaml"
  tags:
    - k8s-master

- name: wait for k8s-apiserver up
  wait_for:
    port: 8080
  tags:
    - k8s-master

# @todo change this to the uri module once ansible 2.1 is stable.
- name: create kube-system namespace
  become: yes
  command: >
    curl -XPOST -d'{"apiVersion":"v1","kind":"Namespace","metadata":{"name":"kube-system"}}' "http://127.0.0.1:8080/api/v1/namespaces"
  run_once: true
  tags:
    - k8s-master
